/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package server_control;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author AlbertusK95
 */
public class TopAdmin extends javax.swing.JFrame {

    private String adminUsername;
    private String adminPassword;
   
    /**
     * Creates new form TopAdmin
     */
    public TopAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelAdminGate = new javax.swing.JLabel();
        labelUsernameAdmin = new javax.swing.JLabel();
        labelPasswordAdmin = new javax.swing.JLabel();
        txtUsernameAdmin = new javax.swing.JTextField();
        txtPasswordAdmin = new javax.swing.JTextField();
        btnLoginAdmin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelAdminGate.setFont(new java.awt.Font("Cambria", 1, 36)); // NOI18N
        labelAdminGate.setText("Admin Gate");

        labelUsernameAdmin.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        labelUsernameAdmin.setText("Username");

        labelPasswordAdmin.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        labelPasswordAdmin.setText("Password");

        btnLoginAdmin.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        btnLoginAdmin.setText("Login");
        btnLoginAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginAdminActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(110, Short.MAX_VALUE)
                .addComponent(labelAdminGate)
                .addGap(97, 97, 97))
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelUsernameAdmin)
                    .addComponent(labelPasswordAdmin))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtUsernameAdmin)
                            .addComponent(txtPasswordAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(btnLoginAdmin)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(labelAdminGate)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelUsernameAdmin)
                    .addComponent(txtUsernameAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPasswordAdmin)
                    .addComponent(txtPasswordAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(btnLoginAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void btnLoginAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginAdminActionPerformed
        // TODO add your handling code here:
        String[] args = {};
        String path_to_adminList;
        int isValid;
        
        adminUsername = txtUsernameAdmin.getText();
        adminPassword = txtPasswordAdmin.getText();
        path_to_adminList = "C:/Users/AlbertusK95/Documents/NetBeansProjects/SayHI/users/admin/admin_list.txt";
        
        // memulai validasi username dan password admin
        AdminValidation av = new AdminValidation(path_to_adminList);
        try {
            isValid = av.validate();
            if (isValid == 1) {
                JOptionPane.showMessageDialog(this, "Admin login is VALID", "Admin Login Status", JOptionPane.PLAIN_MESSAGE);
                ServerAdmin.main(args);
                this.setVisible(false);
            } else {
                JOptionPane.showMessageDialog(this, "Admin login is INVALID", "Admin Login Status", JOptionPane.ERROR_MESSAGE);
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnLoginAdminActionPerformed
    
    private class AdminValidation {
    
        String path;
        
        public AdminValidation(String path) {
            this.path = path;
        }
        
        public int validate() throws IOException {
            
            BufferedReader br = null;
            String sCurrentLine;
            int adminIndex = 0;
            int adminUsernameValid = 0, adminPasswordValid = 0; 
            int validStatus = 0;
            
            try {
                    br = new BufferedReader(new FileReader(path));
                    while ((sCurrentLine = br.readLine()) != null) {
                            //System.out.println(sCurrentLine);
                            if (adminIndex % 2 == 0) {
                                // membaca username admin
                                if (sCurrentLine.equals(adminUsername)) {
                                    adminUsernameValid = 1;
                                }
                            } else {
                                // membaca password admin
                                if (adminUsernameValid == 1) {
                                    if (sCurrentLine.equals(adminPassword)) {
                                        adminPasswordValid = 1;
                                    } 
                                    break;
                                } 
                            }
                            adminIndex++;
                    }
                    
                    if (adminUsernameValid == 1 && adminPasswordValid == 1) {
                        // admin login is valid
                        validStatus = 1;
                    } else {
                        // admin login is not valid
                        validStatus = 0;
                    }
                
            } catch (IOException e) {
                    e.printStackTrace();
            } finally {
                    try {
                        if (br != null) br.close();
                    } catch (IOException e) {
                        e.printStackTrace();
                    }
            }
            return validStatus;
        }
    
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TopAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TopAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TopAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TopAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TopAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLoginAdmin;
    private javax.swing.JLabel labelAdminGate;
    private javax.swing.JLabel labelPasswordAdmin;
    private javax.swing.JLabel labelUsernameAdmin;
    private javax.swing.JTextField txtPasswordAdmin;
    private javax.swing.JTextField txtUsernameAdmin;
    // End of variables declaration//GEN-END:variables
}
