/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package subs_control;

import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.Socket;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author AlbertusK95
 */
public class PrivChatDialog extends javax.swing.JDialog {

    private final String pengirim;
    private final String kepada;
 
    private final Socket socket;
    private final ObjectInputStream input;
    private final ObjectOutputStream output;
 
    /**
     * Creates new form PrivChatDialog
     */
    public PrivChatDialog(SubsHome parent, Socket socket, ObjectInputStream input, ObjectOutputStream output, String pengirim, String kepada) {
        super(parent, false);
 
        this.socket = socket;
        this.input = input;
        this.output = output;
        this.pengirim = pengirim;
        this.kepada = kepada;
        setLocationRelativeTo(parent);
        initComponents();
    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtareaChatHistory = new javax.swing.JTextArea();
        txtChatPost = new javax.swing.JTextField();
        btnSendPrivChat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        txtareaChatHistory.setColumns(20);
        txtareaChatHistory.setRows(5);
        jScrollPane1.setViewportView(txtareaChatHistory);

        txtChatPost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtChatPostActionPerformed(evt);
            }
        });

        btnSendPrivChat.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        btnSendPrivChat.setText("Send");
        btnSendPrivChat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendPrivChatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtChatPost, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSendPrivChat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtChatPost, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSendPrivChat, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void display(String res) {
        txtareaChatHistory.setText(txtareaChatHistory.getText() + res + "\n");
    }
    
    private void btnSendPrivChatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendPrivChatActionPerformed
        // TODO add your handling code here:
        try {
            String message = "postPrivateText~" + pengirim + "~" + txtChatPost.getText() + "~" + kepada + "~\n";
            display(pengirim + ": " + txtChatPost.getText() + "\n");
            output.writeObject(message);
            txtChatPost.setText("");
        } catch (IOException ex) {
            Logger.getLogger(SubsHome.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSendPrivChatActionPerformed

    private void txtChatPostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtChatPostActionPerformed
        // TODO add your handling code here:
        btnSendPrivChatActionPerformed(evt);
    }//GEN-LAST:event_txtChatPostActionPerformed

    /**
     * @param args the command line arguments
     */
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSendPrivChat;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtChatPost;
    private javax.swing.JTextArea txtareaChatHistory;
    // End of variables declaration//GEN-END:variables
}
