/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package subs_control;
        
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;

/**
 *
 * @author AlbertusK95
 */
public class TopSubs extends javax.swing.JFrame {

    private final String path_to_config;
    private String hostname, listeningPort, username, fullname;
    
    /**
     * Creates new form TopSubs
     * @param username
     * @param fullname 
     */
    public TopSubs(String username, String fullname) {
        path_to_config = "C:\\Users\\AlbertusK95\\Documents\\NetBeansProjects\\SayHI\\users\\admin\\server_config.txt";
        this.username = username;
        this.fullname = fullname;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnServerConnect = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnServerConnect.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        btnServerConnect.setText("Connect to Server");
        btnServerConnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnServerConnectActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(139, Short.MAX_VALUE)
                .addComponent(btnServerConnect)
                .addGap(118, 118, 118))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(btnServerConnect)
                .addContainerGap(143, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * GETTER
     */
    private String[] GET_SERVERINFO() {
        BufferedReader br = null;
        String[] serverInfo = new String[2];
        String tempInfo;
        int serverInfoIndex = 0;
        
        try {
            br = new BufferedReader(new FileReader(path_to_config));
            while ((tempInfo = br.readLine()) != null) {
                serverInfo[serverInfoIndex] = tempInfo;
                serverInfoIndex++;
            }
        } catch (IOException e) {
            e.printStackTrace();
        } finally {
            try {
                br.close();
            } catch (IOException e) {
                e.printStackTrace();
            }
        }
        
        return serverInfo;
    }
    
    private void btnServerConnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnServerConnectActionPerformed
        // TODO add your handling code here:
        
        String[] args = new String[4];
        
        // mengambil informasi mengenai hostname dan listening port server
        hostname = GET_SERVERINFO()[0];
        listeningPort = GET_SERVERINFO()[1];
        
        setTitle(hostname + ":" + listeningPort + "/" + username);
        
        // membentuk objek client baru
        args[0] = hostname;
        args[1] = listeningPort;
        args[2] = username;
        args[3] = fullname;
        this.setVisible(false);
        SubsHome.main(args);
    }//GEN-LAST:event_btnServerConnectActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TopSubs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TopSubs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TopSubs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TopSubs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TopSubs(args[0], args[1]).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnServerConnect;
    // End of variables declaration//GEN-END:variables
}
